"""destination table

Revision ID: a1690a2e911b
Revises: 2198c6956374
Create Date: 2023-02-08 15:59:02.352911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1690a2e911b'
down_revision = '2198c6956374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('starts', sa.Date(), nullable=True),
    sa.Column('ends', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('destination', sa.String(length=40), nullable=True),
    sa.Column('number_of_people', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('guide', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_blueprint.id'], ),
    sa.ForeignKeyConstraint(['guide'], ['user_blueprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination')
    # ### end Alembic commands ###
