"""users table updated

Revision ID: f4cc77e4f748
Revises: 9ef4f44079fd
Create Date: 2023-02-21 11:30:51.666530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cc77e4f748'
down_revision = '9ef4f44079fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_again')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_again', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
